namespace IvTem.TypeSafety.Generation;

internal static class EmbeddedAttributeSource
{
    public const string HintName = "IvTem.TypeSafety.EmbeddedAttributes.g.cs";

    public const string Source = """
// <auto-generated />

namespace IvTem.TypeSafety
{
    /// <summary>
    /// Disallows generic type arguments assignable to one of the configured types.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.GenericParameter, AllowMultiple = true)]
    internal sealed class DisallowTypesAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisallowTypesAttribute"/> class.
        /// </summary>
        /// <param name="types">The disallowed type arguments.</param>
        public DisallowTypesAttribute(params global::System.Type[] types)
        {
        }
    }

    /// <summary>
    /// Disallows generic type arguments exactly matching one of the configured types.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.GenericParameter, AllowMultiple = true)]
    internal sealed class DisallowExactTypesAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisallowExactTypesAttribute"/> class.
        /// </summary>
        /// <param name="types">The disallowed exact type arguments.</param>
        public DisallowExactTypesAttribute(params global::System.Type[] types)
        {
        }
    }
}
""";
}
